project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

forum/models.py
from django.db import models
import datetime 
from django.utils import timezone

# Create your models here.
class Pergunta(models.Model):
    titulo = models.CharField(max_length=200, null=False)
    detalhe = models.TextField(null=False)
    tentativa = models.TextField()
    data_criacao = models.DateTimeField("criado em")
    usuario = models.CharField(max_length=200, null=False, default="anonimo")

    def __str__(self):
        return "[" + str(self.id) + "]" + self.titulo
    def foi_publicada_recentemente(self):
        return self.data_criacao >= timezone.now() - datetime.timedelta(days=1)
    def strings_detalhada(self):
        return "id: " +str(self.id) + "; titulo : " +self.titulo + "; detalhe: " +self.detalhe + "; tentativa: " + self.tentativa
    
class Resposta(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    texto = models.TextField(null=False)
    votos = models.IntegerField(null=False)
    data_criacao = models.DateTimeField("criado em")
    usuario = models.CharField(max_length=200, null=False, default="anonimo")

    def __str__(self):
        return "[" + str(self.id) + "]" + self.texto
    def foi_publicada_recentemente(self):
        return self.data_criacao >= timezone.now() - datetime.timedelta(days=1)

forum/views.py
from django.shortcuts import render

# Create your views here.

forum/templates/forum/base.html
<html>
<head>
    <title>Exemplo StackOverflow</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
</head>
<body>
    <header>
        <h1>Fórum MyStackOverflow</h1>
        <nav>
            <a href="{% url 'forum:index' %}">Home</a> | 
            <a href="{% url 'forum:inserir_pergunta' %}">Criar pergunta</a>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

forum/templates/forum/detalhe.html
{% extends "forum/base.html" %}

{% block content %}
<h2>{{ pergunta.titulo }}</h2>
<p><b>Descrição:</b> {{ pergunta.detalhe }}</p>
<p><b>Tentativas:</b> {{ pergunta.tentativa }}</p>
<p><b>Data:</b> {{ pergunta.data_criacao|date:"d/m/Y H:i" }}</p>
<p><b>Autor:</b> {{ pergunta.usuario }}</p>
{% block respostas %}
<h3>Respostas</h3>
<ul>
{% for resposta in pergunta.resposta_set.all %}
    <li>
        {{ resposta.texto }} - <b>{{ resposta.votos }} votos</b>
        <form action="{% url 'forum:voto' resposta.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Votar">
        </form>
    </li>

{% endfor %}
</ul>
<a href="{% url 'forum:inserir_resposta' pergunta.id %}">
    <button>Nova resposta</button>
</a>
{% endblock %}
{% endblock %}

forum/templates/forum/index.html
{% extends "forum/base.html" %}

{% block content %}
{% if perguntas %}
    <h2>Últimas perguntas</h2>
    <ul>
    {% for pergunta in perguntas %}
        <li>
            <a href="{% url 'forum:detalhe' pergunta.id %}">
                {{ pergunta.titulo }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nenhuma pergunta disponível.</p>
{% endif %}
<a href="{% url 'forum:inserir_pergunta' %}">
    <button>Nova pergunta</button>
</a>
{% endblock %}